services:
  - type: web
    name: tflow-medical-triage
    runtime: python3
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python main.py"
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false  
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
